version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    # create a single pull request containing all updates for GitHub Actions
    github-actions:
      patterns:
      - '*'
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: docker
  directory: /
  schedule:
    interval: monthly
